# Autogenerated wrapper script for SISL_jll for i686-w64-mingw32
export libsisl

JLLWrappers.@generate_wrapper_header("SISL")
JLLWrappers.@declare_library_product(libsisl, "libsisl.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libsisl,
        "bin\\libsisl.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
